### ISSUE TITLE
About "ingress-based overlay"

### ISSUE THREAD

**Issue by Deguello1** [boucadair/CATS-framework#13]
> ingress-based overlay

This should be elaborated as it suggests some directionality that is debatable.

**Comment by boucadair** [comment]
I'm not sure there is a value in maintaining that wording, either. 

The directionality is relevant as the placement decision is made when first receiving an incoming request but that's obvious and does not need to be called out.

**Comment by VMatrix1900** [comment]
The text is removed. This issue can be closed?

**Comment by boucadair** [comment]
Already removed in draft-ldbc-cats-framework-03
