### ISSUE TITLE
About the forwarding role of CATS classifiers

### ISSUE THREAD

**Issue by Deguello1** [boucadair/CATS-framework#18]
> forwarded along the same path

The current wording implicitly suggests there's no room for traffic load balancing. I would relax (or clarify) this a bit as the outcomes of C-PS ccomputation may very well encourage traffic load distribution as a function of the traffic ocngestion conditions, possibly leading to multi-path forwarding policies towards a given service instance.

**Comment by VMatrix1900** [comment]
I would remove "along the same path" and only keep "towards the same service contact instance".

**Comment by muzixing** [comment]
can be closed after merging the text. Thanks Med's text
