### ISSUE TITLE
About egress/ingress taxonomy

### ISSUE THREAD

**Issue by Deguello1** [boucadair/CATS-framework#19]
> The Egress CATS-Routers are the egress endpoints of overlay paths

I fail to see the need for this. Again, this suggests (unnecessary) distinction between two types of CATS routers at the risk of obliterating the very likely heuristic.

**Comment by boucadair** [comment]
Reasoning about directionality (in reference to service placement requests) has the merit to easily identify the nodes and whether they need to perform specific features. The ingress/egress thing if you will is similar to the ITR/ETR in LISP.

Added this note to -01:

> Note: "Egress" is used here in reference the direction of the  service request placement.  The directionality is called to
>            explicitly identify the exit node of the CATS infrastructure.

I prefer to leave this terminology now but reassess the point (simplify the terminology) when we will have a more stable text. Thanks @Deguello1.

**Comment by muzixing** [comment]
Agree with Med that keep the text. This has been dicussed in the WG, so we need to define two roles. Ingress and Egress CATS-Forwarder.
