### ISSUE TITLE
About CATS (C-PS) implementation

### ISSUE THREAD

**Issue by Deguello1** [boucadair/CATS-framework#21]
> A CATS implementation may rely upon a control plane or a management plane  to distribute service metrics and network metrics - this document does not define a specific solution.

I'm not sure I would keep this unless further elaboration is provided. In addition, the initial text mentions underlay nodes (as far as metric distribution is concerned), which somewhat contradicts the previous statement about the underlay/overlay taxonomy: if CATS routers are not supposed to be involved in the IP/MPLS control and forwarding planes of the so-called underlay, then what's the point of feeding underlay nodes with CATS metrics?

**Comment by VMatrix1900** [comment]
I do not understand why put this paragraph in the Underlay Infrastructure section. Is the control plane or management plane refers to the control/management plane of the underlay infratructure?

**Comment by VMatrix1900** [comment]
The underlay nodes should not be affected by CATS metrics.
