### ISSUE TITLE
Is C-NMA expected to use existing solutions?

### ISSUE THREAD

**Issue by boucadair** [boucadair/CATS-framework#28]
(From Luis) 

> I see we mention several times about “network state”, with the idea that the C-NMA will handle such information. I guess network state can be define using existing solutions/metrics. The question is, do we expect in CATS to define something in this respect on how to feed the C-NMA or what kind of existing information/metrics the C-NMA will lever on, or not? If not, probably we can state that C-NMA is expected to use existing solutions/metrics, maybe providing some reference as well, and concentrate on C-SMA.

**Comment by VMatrix1900** [comment]
Exisiting network metric such as RTT, loss, bandwidth seems enough. RFC8571 defines various performance metric extension to BGP-LS.

**Comment by muzixing** [comment]
I think C-NMA is expected to use existing solutions.
