### ISSUE TITLE
(IETF#116 Comments) What is computing?

### ISSUE THREAD

**Issue by boucadair** [boucadair/CATS-framework#29]
-	What is computing? What is computation? (This is a big thing to
agree on. It needs discussion on the list)

**Comment by muzixing** [comment]
ok, let's leave it here and ask in the list once we update the draft. To me, it is quite clear. But we might can not define a perfect term to be comfortable to anyone :)

**Comment by boucadair** [comment]
The draft was updated as per https://datatracker.ietf.org/meeting/117/materials/slides-117-cats-service-service-instance-other-cats-concepts-00
