### ISSUE TITLE
(IETF#116 Comments) Inputs from draft-shi-cats-analysis-of-metric-distribution

### ISSUE THREAD

**Issue by boucadair** [boucadair/CATS-framework#33]
-	Look at draft-shi-cats-analysis-of-metric-distribution and see what
could move into this document (Would need to work with the authors of that draft and invite them to join the framework as contributors)

**Comment by boucadair** [comment]
Not sure there is material that can be moved to the framework. Please see https://github.com/boucadair/IETF-Drafts-Reviews/raw/master/draft-shi-cats-analysis-of-metric-distribution-00-rev%20Med.pdf

**Comment by VMatrix1900** [comment]
draft-shi-cats-analysis-of-metric-distribution is based on the framework draft, not the other way around. There is no material that can be moved to the framework.
