### ISSUE TITLE
(Section 4.4) Pull/Push Modes

### ISSUE THREAD

**Issue by boucadair** [boucadair/CATS-framework#49]
Section 4.4 have the following, which may seem to be contradicting:

> In the example shown in [Figure 2](https://boucadair.github.io/CATS-framework/draft-ldbc-cats-framework.html#fig-cats-example-overlay), when the client sends a service request to "CATS-Forwarder 1", the forwarder solicits the C-PS to select a service contact instance hosted by a service site that can be accessed through a particular Egress CATS-Forwarder.

and

> The Ingress CATS-Forwarder classifies incoming packets received from clients by soliciting the CATS classifier (C-TC). When a matching classification entry is found for the packets, the Ingress CATS-Forwarder encapsulates and forwards them to the C-PS selected Egress CATS-Forwarder. 

We need to discuss if we allow both Pull/Push modes or only a mode. Then, make sure we are consistent in the doc

**Comment by VMatrix1900** [comment]
I think both modes has its own merit. Pull mode is suitable for centralized C-PS and can get better overall usage result. Push mode is suitable for distributed C-PS and does not introduce the pull latency. Please see [Hybrid Solution draft](https://datatracker.ietf.org/doc/draft-yi-cats-hybrid-solution/) and [its slides](https://datatracker.ietf.org/meeting/118/materials/slides-118-cats-3a-hybird-computing-and-network-awareness-and-routing-architecture-for-cats-00.pdf) for detailed discussion.

**Comment by muzixing** [comment]
I think both modes are needed. However, in this section, I do not think the text emphasize this. 
It describes the processing of first packet and the following packets. so we may rephrase it as 

In the example shown in [Figure 2](https://datatracker.ietf.org/doc/html/draft-ldbc-cats-framework-03#fig-cats-example-overlay), the client sends a service access to the network though the "CATS-Forwarder 1" that is an Ingress CATS-Forwarder.
Note that, a service access consists of one or more service packets. The Ingress CATS-Forwarder classifies incoming packets received from clients by the information provided by the CATS classifier (C-TC). When a matching classification entry is found for the packets, the Ingress CATS-Forwarder encapsulates and forwards them to the C-PS selected Egress CATS-Forwarder. When these packets reach the Egress CATS-Forwarder, the outer header of the possible overlay encapsulation is removed and inner packets are sent to the relevant service contact instance.

what do  you think?

**Comment by muzixing** [comment]
This has been closed by https://github.com/boucadair/CATS-framework/pull/54
