### ISSUE TITLE
Editorial comments of Computing-aware forwarding definition

### ISSUE THREAD

**Issue by muzixing** [boucadair/CATS-framework#52]
Computing-aware forwarding (or steeting, computing):
A forwarding (or steeting, computing) scheme which takes as input a set of metrics that reflect the capabilities and state of computing resources.

The syntax seems incorrect or hard to be understood.
hope to make it clear for readers.

**Comment by muzixing** [comment]
A forwarding (or steering, computing) scheme which takes a set of metrics that reflect the capabilities and state of computing resources as input.

is it ok?

**Comment by boucadair** [comment]
Not sure how the proposed NEW is better that the OLD

**Comment by muzixing** [comment]
'takes as input a set of metrics that' seems too complicated in syntax, but put 'as input' in the end can help readers to know, the metrics is treated as input. At least to me, it is better.
