### ISSUE TITLE
A clarification problem about definition of Service contact instance

### ISSUE THREAD

**Issue by dzpzp** [boucadair/CATS-framework#69]
Currently, in the draft, it is described  that:

Service contact instance:
A client-facing service function instance that is responsible for receiving requests in the context of a given service. A service request is processed according to the service logic (e.g., handle locally or solicit backend resources). Steering beyond the service contact instance is hidden to both clients and CATS components.[¶](https://github.com/boucadair/CATS-framework/issues/new#section-2-2.32.1)
a service contact instance is reachable via at least one Egress CATS Forwarder.
A service can be accessed via multiple service contact instances running at the same or different locations (service sites).
The same service contact instance may dispatch service requests to one or more service instances (e.g., ***an instance*** that behaves as a service load-balancer).

    I wonder what the ***an instance*** means here. Is it a Service contact instance, or a  service instance ?

IMO, it is a Service contact instance. Thus, it can be changed to:

The same service contact instance may dispatch service requests to one or more service instances (e.g., ***a service contact instance*** that behaves as a service load-balancer).
. 

If I misunderstand it, please correct me, thanks.

I also posted an email about the problem, and I hope to obtain some feedback here.

**Comment by muzixing** [comment]
Interesting comment. Thanks for that! The update looks reasonable to me. How about let me make it more clear like below:

The same service contact instance may dispatch service requests to one or more service instances. When a service contact instance dispatch the service requiest to multiple service instances, it behaves as a service load-balancer.

**Comment by boucadair** [comment]
I like more the update from dz

> (e.g., _**a service contact instance**_ that behaves as a service load-balancer).
> .

Looks good to me. I prefer this over the @muzixing's proposal. Thanks.

**Comment by muzixing** [comment]
No Problem to me, we can use Zongpeng's proposal
