### ISSUE TITLE
Description about the service contact instance in a single service site

### ISSUE THREAD

**Issue by dzpzp** [boucadair/CATS-framework#79]
In the introduction，the 4th paragraph，

Old
A single service site may host one or multiple service contact instances.
New1
A single service site may host one or multiple service instances, and one or multiple related service contact instances.
Or New2
A single service site may host one service instance for a given service, and in this case one associated service contact instance; meanwhile, a single service site may host multiple service instances for a given service, and in this case one or multiple associated service contact instances.

Reason of suggestion:
It is a little hard for a new reader of the draft to understand the relationship among a service site, service instances, and the service contact instance.
IMHO, more explanation should be added here or someplace else.

**Comment by muzixing** [comment]
Well, this is also about the service contact instance. Please see details in emails.

**Comment by muzixing** [comment]
closed as addressed by PR#91
