### ISSUE TITLE
Description about networking resources in computing resources

### ISSUE THREAD

**Issue by dzpzp** [boucadair/CATS-framework#80]
2. Terminology

Old
Computing Service:
An offering is made available by a provider by orchestrating a set of computing resources (without networking resources).¶

New
An offering is made available by a provider by orchestrating a set of computing resources (without networking resources in the network domain).

Reason of suggestion:
In fact, the server has network cards, which can be regards as networking resources. However, it is on the host, and belongs to the computing domain.

So, maybe some explanation can be added here.

**Comment by muzixing** [comment]
agree.

**Comment by muzixing** [comment]
BTW, this part will be updated to sync up with the definition in use case draft. see issue https://github.com/boucadair/CATS-framework/issues/90
