### ISSUE TITLE
Description about forwarding decision on CATS-Forwarder

### ISSUE THREAD

**Issue by dzpzp** [boucadair/CATS-framework#81]
2. Terminology

Old
CATS-Forwarder:
A network entity that makes forwarding decisions based on CATS information to steer traffic specific to a service request towards a corresponding yet selected service contact instance.

New:
A network entity that steers traffic specific to a service request towards a corresponding yet selected service contact instance according to the forwarding decisions made by the decision point based on CATS information. The decision point, which is on the C-PS, is responsible for making the steering policy, and it may or may not on the CATS-Forwarder.

Reason of suggestion:
The CATS-Forwarder may or may not be the decision point for CATS.

**Comment by muzixing** [comment]
Agree, good catch!
