### ISSUE TITLE
Description about C-TC

### ISSUE THREAD

**Issue by dzpzp** [boucadair/CATS-framework#82]
2. Terminology

old
CATS Traffic Classifier (C-TC):
A functional entity that is responsible for determining which packets belong to a traffic flow for a particular service request. It is also responsible for forwarding such packets along a C-PS computed path that leads to the relevant service contact instance.

New:
A functional entity that is responsible for determining which packets belong to CATS, and additionally, it may distinguish which packets belong to a traffic flow for a particular service request. It is also responsible for forwarding such packets along a C-PS computed path that leads to the relevant service contact instance.

Reason of suggestion:
Some services for CATS, perhaps, do not need this Service Contact Instance Affinity. However, their traffic should also be recognized and forwarded to a service contact instance. 
So, IMHO, the function of the C-TC should be described more generally. 

3.4.5. CATS Traffic Classifier (C-TC)

Old
CATS Traffic Classifier (C-TC) is a functional component that is responsible for associating incoming packets from clients with existing service requests. CATS classifiers also ensure that packets that are bound to a specific service contact instance are all forwarded towards that same service contact instance, as instructed by a C-PS.

New
CATS Traffic classifier (C-TC) is a functional component that is responsible for CATS traffic classification, and it may also be responsible for associating incoming packets from clients with existing service requests.
CATS classifiers can ensure that packets that are bound to a specific service contact instance are all forwarded towards that same service contact instance if needed, as instructed by a C-PS.

**Comment by muzixing** [comment]
see email discussion.

**Comment by muzixing** [comment]
close after sync up with zongpeng. The PR#91 can address his comments
