### ISSUE TITLE
Description about globally unique of CS-ID

### ISSUE THREAD

**Issue by dzpzp** [boucadair/CATS-framework#83]
3.4.1. Service Sites, Services Instances, and Service Contact Instances

Old
The CS-ID does not need to be globally unique, though.

New
The CS-ID does not need to be globally unique, though, for example, in the case of CATS working in a limited domain.

Reason of suggestion:
IMHO, it is better to give some explanation here.

Limited Domains and Internet Protocols
https://datatracker.ietf.org/doc/html/rfc8799
It has been talked before; however, some explanation may be helpful here.

**Comment by muzixing** [comment]
OK
