### ISSUE TITLE
Modification about 3.4.6. Overlay CATS-Forwarders

### ISSUE THREAD

**Issue by dzpzp** [boucadair/CATS-framework#84]
3.4.6. Overlay CATS-Forwarders

Old
 If a C-PS has selected a specific service contact instance and the C-TC has marked the traffic with the CIS-ID, the Egress CATS-Forwarder then forwards traffic to the relevant service contact instance. 

New
If a C-PS has selected a specific service contact instance and the C-TC has marked the traffic with the CIS-ID related information, the Egress CATS-Forwarder then forwards traffic to the relevant service contact instance according the information.

Reason of suggestion:
IMHO, it is better to describe more generally here. It is not a MUST CID-ID is marked directly in the packet.

**Comment by muzixing** [comment]
it looks good to me.
