### ISSUE TITLE
Description about Centralized designs and Centralized model in 3.5. Deployment Considerations

### ISSUE THREAD

**Issue by dzpzp** [boucadair/CATS-framework#85]
3.5. Deployment Considerations

Old
In the latter case, the CATS computation logic may process incoming service requests to compute and select paths and, therefore, service contact instances. 

New
In this case, the CATS computation logic may process incoming service requests to compute and select paths and, therefore, service contact instances. Or for a specific service, the CATS computation logic can compute and select paths in advance.

Reason of suggestion:
IMHO, if the controller needs to compute the path after obtaining an incoming service request packet, it is on-demand but slow.
If the controller is configured to collect the information about a specific service, it can computer the path without receiving an incoming service request packet.

Old

Centralized model:
Computing metrics are collected by a centralized control plane, and then the centralized control plane performs service scheduling function, and computes the forwarding path for service requests and syncs up with the Ingress CATS-Forwarder.

New
Centralized model:
Computing metrics are collected by a centralized control plane, and then the centralized control plane computes the forwarding path and syncs up with the Ingress CATS-Forwarder.

Reason of suggestion:
IMHO, the service scheduling is related, but may be out of the scope of CATS. So, no need to emphasize it here.

**Comment by muzixing** [comment]
I agree with you about the service scheduling part. Please see more reply in email.

**Comment by muzixing** [comment]
closed after sync up with zongpeng
