### ISSUE TITLE
Modification of 4.3. Metrics Distribution

### ISSUE THREAD

**Issue by dzpzp** [boucadair/CATS-framework#86]
4.3. Metrics Distribution

Old
Additionally, the C-NMA collects network-related capabilities and metrics. These may be collected and distributed by existing routing protocols, although extensions to such protocols may be required to carry additional information (e.g., link latency).

New
Additionally, the C-NMA collects network-related capabilities and metrics. These may be collected and distributed by existing measurement protocols and/or routing protocols, although extensions to such protocols may be required to carry additional information (e.g., link latency).

Reason of suggestion:
IMHO, most straightforwardly, the C-NMA can measure the delay between the Ingress and the Target Egress as the metric of the network.

**Comment by muzixing** [comment]
It is ok
