### ISSUE TITLE
Modification of 4.5. Service Contact Instance Affinity

### ISSUE THREAD

**Issue by dzpzp** [boucadair/CATS-framework#88]
4.5. Service Contact Instance Affinity
Old
 Specifically, the same Egress CATS-Forwarder may be sollicited to forward the packets.
 
New
 Specifically, the same Egress CATS-Forwarder may be solicited to forward the packets.
 

 Old
The affinity is determined at the time of newly formulated service requests.
 
New
The affinity is configured on the C-PS when the service is deployed, or is determined at the time of newly formulated service requests.

Reason of suggestion:
IMHO, some services, such as the Video on Demand in CDN system, can be without the Service Contact Instance Affinity by default.

**Comment by muzixing** [comment]
ACK. Will update accordingly.
