### ISSUE TITLE
Synchronize the definition on "Computing Service"

### ISSUE THREAD

**Issue by bpatient78** [boucadair/CATS-framework#90]
"Computing Service" in CATS-framework:
Computing Service:  An offering is made available by a provider by orchestrating a set of computing resources (without networking resources).

"Computing Service" in CATS-Use cases & Requirements:
 Computing Service:  An offering that is made available by a provider by orchestrating a set of computing resources to process application content.
 Some differences and similarities exist between service and computing service:
* Service is packet-based, while computing service is transaction-based.  Application content is exposed within a computing service.
* Both service and computing service can be "on-path" or on "endpoint", depending on the service logic or computing service logic that are defined by the provider.

Sugguest CATS-framework adopt the definition on "Computing Service", This is from the dicussion on list https://mailarchive.ietf.org/arch/browse/cats/?q=service

**Comment by muzixing** [comment]
Ack. Will update it in the next revision.
